services:

  php:
    build:
      context: .             
      dockerfile: docker/php/Dockerfile
    container_name: php83_app 
    volumes:
      - ./src:/var/www  
    networks:
      - website1         
    environment:
      PHP_IDE_CONFIG: serverName=Docker # For Xdebug
    restart: unless-stopped

  nginx:
    image: nginx:latest  
    container_name: nginx_app
    ports:
      - "3000:80"         
    volumes:
      - ./src/public:/var/www/public  
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php                 
    networks:
      - website1
    restart: unless-stopped

networks:
  website1:

